services:
  - type: web
    name: tesla-parts-bot
    runtime: docker
    plan: free
    buildCommand: docker build -t tesla-parts-bot .
    startCommand: npm run bot:webhook
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_WEBHOOK
        value: true
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        fromService:
          type: web
          name: tesla-parts-bot
          property: host
        value: https://$HOST/api/telegram/webhook
      - key: FRONTEND_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: VITE_IMGBB_API_KEY
        sync: false
      - key: VITE_GOOGLE_API_KEY
        sync: false
      - key: VITE_GOOGLE_CX
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
    healthCheckPath: /
    autoDeploy: false